// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gcoflpvgheedxbvrxeny.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imdjb2ZscHZnaGVlZHhidnJ4ZW55Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAwNzc1NDMsImV4cCI6MjA2NTY1MzU0M30.OClGIQBDrLyzSWGnvQbtlMx4UqMByslsJvsQD_f1BmI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);